classes:
  - common
  - my_component
  - generators.bmh_ma
parameters:
  target_name: my_target
  subnets:
    storage-access:
      cidr: 10.0.0.0/24
    storage-backend:
      cidr: 10.1.0.0/24
    tenant:
      cidr: 10.2.0.0/24
    floating:
      cidr: 10.3.0.0/24
  cluster:
    name: name
    namespace: child
    provider: baremetal
    region: region-one
    release: release
    publicKey: key
    metallbPool: pool
    loadBalancerHost: lb
    network:
      podsCidr: podcidr
      servicesCidr: servicecidr
  hosts:
    managers:
      l2template:
        name: managers
      names:
      - node01
    workers_generics:
      nodeLabels:
        test: foo
      names:
      - node02
    workers_osctl:
      BMHProfile:
        name: control
        namespace: child
      names:
      - node03
  nodes:
    node01:
      macAddress: 52:54:00:b6:ed:31
      bmcAddress: redfish+http://10.23.25.1:8000/redfish/v1/Systems/air-target-1
      bootUEFI: false
      bmcUsername: root
      bmcPassword: r00tme
    node02:
      macAddress: 00:3b:8b:0c:ec:8b
      bmcAddress: redfish+http://10.23.25.2:8000/redfish/v1/Systems/air-target-2
      bootUEFI: false
      bmcUsername: username
      bmcPassword: password
    node03:
      macAddress: 00:3b:8b:0c:ec:c8
      bmcAddress: redfish+http://11.23.25.2:8000/redfish/v1/Systems/air-target-2
      bootUEFI: false
      bmcUsername: username
      bmcPassword: password
