apiVersion: airshipit.org/v1alpha1
kind: Templater
metadata:
  name: l2template-template
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: quay.io/airshipit/templater:latest

template: |
  {{ if .ipam.l2template }}
  ---
  apiVersion: ipam.mirantis.com/v1alpha1
  kind: L2Template
  metadata:
    labels:
      ipam/Cluster: {{ .commonCluster.clusterName }}
    name: {{ .ipam.l2template.name }}
  spec:
    autoIfMappingPrio:
    {{- range .ipam.l2template.autoIfMappingPrio }}
    - {{ . }}
    {{- end}}
    npTemplate: |-
  {{ .ipam.l2template.template | indent 4 }}
  {{ end -}}
