apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../function/subnetGenerator
  - ../../shared
transformers:
  - ../../../function/subnetGenerator/replacements
  - cleanup.yaml
