{% set i = inventory.parameters %}
{% set f = i.hosts %}
{% for subtype, values in f.items() %}
{% for m in values.names %}
---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: {{ m }}
  namespace: {{ i.cluster.namespace }}
  labels:
    cluster.sigs.k8s.io/cluster-name: {{ i.cluster.name }}
    kaas.mirantis.com/provider: {{ i.cluster.provider }}
    kaas.mirantis.com/region: {{ i.cluster.region }}
    {% if subtype == 'workers_storage' %}
    hostlabel.bm.kaas.mirantis.com/storage: 'true'
    {% endif %}
spec:
  providerSpec:
    value:
      apiVersion: "baremetal.k8s.io/v1alpha1"
      kind: "BareMetalMachineProviderSpec"
      {% if 'BMHProfile' in values %}
      bareMetalHostProfile:
        name: {{ values['BMHProfile']['name'] }}
        namespace: {{ values['BMHProfile']['namespace'] }}
      {% endif %}
      {% if 'l2template' in values %}
      l2TemplateSelector:
        name: {{ values['l2template']['name'] }}
      {% endif %}
      hostSelector:
        matchLabels:
          baremetal: hw-{{ m }}
      nodeLabels:
      {% if 'nodeLabels' in values %}
      {% for k,v in values['nodeLabels'].items() %}
      - key: {{ k }}
        value: {{ v }}
      {% endfor %}
      {% endif %}
      {% if subtype == 'workers_osctl' %}
      - key: openvswitch
        value: enabled
      - key: openstack-control-plane
        value: enabled
      - key: openstack-gateway
        value: enabled
      {% elif subtype == 'workers_oscmp' %}
      - key: openvswitch
        value: enabled
      - key: openstack-compute-node
        value: enabled
      {% endif %}
{% endfor %}
{% endfor %}
