apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../function/k8smachines
  - ../../../shared
transformers:
  - ../../../../function/k8smachines/replacements
  - flattener.yaml 
  - cleanup.yaml
