# Site-level host catalogue.  This info feeds the Templater
# kustomize plugin config in the hostgenerator-m3 function.
apiVersion: airshipit.org/v1alpha1
kind: VariableCatalogue
metadata:
  name: host-catalogue
hosts:
  m3:
    node01:
      macAddress: 52:54:00:b6:ed:31
      bmcAddress: redfish+http://10.23.25.1:8000/redfish/v1/Systems/air-target-1
      bootUEFI: false
      bmcUsername: root
      bmcPassword: r00tme
    node02:
      macAddress: 00:3b:8b:0c:ec:8b
      bmcAddress: redfish+http://10.23.25.2:8000/redfish/v1/Systems/air-target-2
      bootUEFI: false
      bmcUsername: username
      bmcPassword: password
    node03:
      macAddress: 00:3b:8b:0c:ec:c8
      bmcAddress: redfish+http://11.23.25.2:8000/redfish/v1/Systems/air-target-2
      bootUEFI: false
      bmcUsername: username
      bmcPassword: password
