# The default networking catalogue for functions hosted in the airshipctl project.
# These values can be overridden at the site, type, etc levels as appropriate.
apiVersion: airshipit.org/v1alpha1
kind: VariableCatalogue
metadata:
  name: networking
kubernetes:
  serviceCidr: "10.96.0.0/12"
  podCidr: "192.168.0.0/18"
  dnsNameservers: 8.8.8.8
  loadBalancerHost: 172.20.20.2
  addressPools: 172.20.20.3-172.20.20.100
ipam:
  subnets:
    storage-frontend:
      cidr: 10.114.0.0/27
    storage-backend:
      cidr: 10.115.0.0/27
    tenant:
      cidr: 10.116.0.0/27
  #TODO: What if we do not need custom l2template, ipam.l2template check needed
  l2template:
    name: test
    autoIfMappingPrio:
    - provision
    - eno
    - ens
    - enp
    template: |-
      version: 2
      ethernets:
        {{nic 0}}:
          dhcp4: false
          dhcp6: false
          addresses:
            - {{ip "0:master-region-one"}}
          gateway4: {{gateway_from_subnet "master-region-one"}}
          nameservers:
            addresses: {{nameservers_from_subnet "master-region-one"}}
          match:
            macaddress: {{mac 0}}
          set-name: {{nic 0}}
          mtu: 1500
