{% set i = inventory.parameters %}
apiVersion: cluster.k8s.io/v1alpha1
kind: Cluster
metadata:
  name: {{ i.cluster.name }} 
  namespace: {{ i.cluster.namespace }}
  labels:
    kaas.mirantis.com/provider: {{ i.cluster.provider }}
    kaas.mirantis.com/region: {{ i.cluster.region }}
spec:
  clusterNetwork:
    services:
      cidrBlocks:
        - {{ i.cluster.network.servicesCidr}} 
    pods:
      cidrBlocks:
        - {{ i.cluster.network.podsCidr}}
  providerSpec:
    value:
      apiVersion: baremetal.k8s.io/v1alpha1
      kind: BaremetalClusterProviderSpec
      release: {{ i.cluster.release }} 
      loadBalancerHost: {{ i.cluster.loadBalancerHost }} 
      dedicatedControlPlane: true
      helmReleases:
        - name: metallb
          values:
            configInline:
              address-pools:
                - name: default
                  protocol: layer2
                  addresses:
                    - {{ i.cluster.metallbPool }} 
        - name: ceph-controller
        - name: stacklight
          {% if 'stacklight' in i.cluster %}
          values:
            {% if 'HAEnabled' in i.cluster.stacklight %}
            highAvailabilityEnabled: {{ i.cluster.stacklight.HAEnabled }}
            {% endif %}
            {% if 'loggingEnabled' in i.cluster.stacklight %}
            logging:
              enabled: {{ i.cluster.stacklight.loggingEnabled }}
            {% endif %}
            {% if 'emailAlert' in i.cluster.stacklight %}
            alertmanagerSimpleConfig:
              email:
                enabled: true
                send_resolved: {{ i.cluster.stacklight.emailAlert.send_resolved }}
                tls:
                  require_tls: {{ i.cluster.stacklight.emailAlert.require_tls }}
                auth_identity: {{ i.cluster.stacklight.emailAlert.auth_identity }}
                auth_password: {{ i.cluster.stacklight.emailAlert.auth_password }}
                auth_secret: {{ i.cluster.stacklight.emailAlert.auth_secret }}
                auth_username: {{ i.cluster.stacklight.emailAlert.auth_username }}
                from: {{ i.cluster.stacklight.emailAlert.from }}
                to: {{ i.cluster.stacklight.emailAlert.to }}
                smarthost: {{ i.cluster.stacklight.emailAlert.smarthost }}
            {% endif %}
          {% endif %}
      kaas:
        management:
          enabled: false
      publicKeys:
      - name: {{ i.cluster.publicKey }} 
