apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../function/hostgenerator-m3
  - ../../shared
transformers:
  - ../../../function/hostgenerator-m3/replacements
  - flattener.yaml
  - cleanup.yaml
