apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: flattener 
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: quay.io/airshipit/replacement-transformer:latest
replacements:
- source:
    objref:
      name: host-generation-catalogue
    fieldref: "{.hosts.m3.managers}"
  target:
    objref:
      kind: Templater
      name: m3-host-template
    fieldrefs: ["{.values.hostsToGenerate}"]
