apiVersion: airshipit.org/v1alpha1
kind: Templater
metadata:
  name: machine-template
  annotations:
    config.kubernetes.io/function: |-
      container:
        image: quay.io/airshipit/templater:latest

template: |
  {{- $envAll := . }}
  {{- range .hostsToGenerate }}
  {{- $hostName := .name }}
  {{- $nodeLabels := .nodeLabels }}
  {{- $bareMetalHostProfile:= .BMHProfile }}
  {{- $l2TemplateSelector:= .l2template }}
  {{- $host := index $envAll.hosts $hostName }}
  ---
  apiVersion: "cluster.k8s.io/v1alpha1"
  kind: Machine
  metadata:
    name: {{ $hostName }}
    labels:
      cluster.sigs.k8s.io/cluster-name: {{ $envAll.commonCluster.clusterName }}
    annotations:
  spec:
    providerSpec:
      value:
        apiVersion: "baremetal.k8s.io/v1alpha1"
        kind: "BareMetalMachineProviderSpec"
        {{- if $bareMetalHostProfile }}
        bareMetalHostProfile:
          name: {{ $bareMetalHostProfile.name }}
          #TODO: seems like having namespace aside metadata is problem. Avoid it 
          namespace: {{ $bareMetalHostProfile.namespace }}
        {{- end }}
        {{- if $l2TemplateSelector }}
        l2TemplateSelector:
          name: {{ $l2TemplateSelector.name }}
        {{- end }}
        hostSelector:
          matchLabels:
            baremetal: hw-{{ $hostName }}
  {{ end -}}
