apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bmh
  - k8s
  - publicKey
  - ipam
commonLabels:
  kaas.mirantis.com/provider: baremetal
  kaas.mirantis.com/region: region-one
namespace: test
