apiVersion: cluster.k8s.io/v1alpha1
kind: Cluster
metadata:
  name: FOOBAR
spec:
  clusterNetwork:
    services:
      cidrBlocks:
        - FOOBAR10.233.128.0/18
    pods:
      cidrBlocks:
        - FOOBAR10.233.192.0/18
  providerSpec:
    value:
      apiVersion: baremetal.k8s.io/v1alpha1
      kind: BaremetalClusterProviderSpec
      # Set from KaaSRelease during bootstrap process
      release: FOOBARmosk-6-8-1
      # Will be set during bootstrap.
      # Must be out of 172.16.45.100-172.16.45.120
      loadBalancerHost: FOOBAR172.16.45.92
      dnsNameservers:
      # default valid for US ICM cloud
        - FOOBAR172.18.224.6
      # use this value for EU ICM cloud
      #- 172.18.176.6
      dedicatedControlPlane: true
      helmReleases:
        - name: metallb
          values:
            configInline:
              address-pools:
                - name: default
                  protocol: layer2
                  addresses:
                    - FOOBAR172.16.45.100-172.16.45.120
        - name: ceph-controller
          values: {}
        - name: stacklight
      kaas:
        management:
          enabled: false
      publicKeys:
      - name: FOOBARbootstrap-key
